spring.application.name=app

# ===============================
# Configuração do Banco de Dados
# ===============================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configurações do JPA / Hibernate
# ===============================
# Faz o Hibernate criar ou atualizar as tabelas com base nas suas entidades (@Entity)
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado no console (ótimo para debug)
spring.jpa.show-sql=true

# Formata o SQL no console para ficar legível
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do banco de dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect