spring.application.name=app

# ===============================
# Configuração do Banco de Dados
# ===============================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configurações do JPA / Hibernate
# ===============================
# Valida se o schema do banco bate com as entidades (@Entity) ? as tabelas são criadas pelo Flyway
spring.jpa.hibernate.ddl-auto=validate

# Mostra o SQL gerado no console (ótimo para debug)
spring.jpa.show-sql=true

# Formata o SQL no console para ficar legível
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do banco de dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Configurações do Flyway
# ===============================
# Habilita o Flyway para gerenciar as migrações do banco
spring.flyway.enabled=true

# Local onde o Flyway busca os scripts de migração
spring.flyway.locations=classpath:db/migration

